//
//  NoZ Hello World Example — Generated by Hekate + noz-ai
//
//  Background scene generated via noz-ai (FluxDev).
//  Layout guided by Hekate design verdict: container-stack, immediate-mode,
//  static style structs with Resolve callbacks for zero-alloc state changes.
//

using NoZ;
using NoZ.Examples;

namespace HelloWorld;

public class HelloWorldApp : IApplication
{
    private Texture? _background;
    private int _clickCount;

    private static readonly ContainerStyle RootStyle = new()
    {
        Size = new Size2(Size.Percent(1), Size.Percent(1)),
        Align = Align.Center,
    };

    private static readonly ImageStyle BackgroundStyle = new()
    {
        Size = new Size2(Size.Percent(1), Size.Percent(1)),
        Stretch = ImageStretch.Fill,
        Order = 0,
    };

    private static readonly ContainerStyle BoxStyle = new()
    {
        Size = Size2.Fit,
        Color = new Color(15, 15, 40, 200),
        Padding = new EdgeInsets(48, 64, 48, 64),
        BorderRadius = 16,
        Spacing = 24,
    };

    private static readonly LabelStyle TitleStyle = new()
    {
        FontSize = 36,
        Color = Color.White,
    };

    private static readonly LabelStyle CountStyle = new()
    {
        FontSize = 18,
        Color = new Color(180, 200, 255),
    };

    private static readonly ButtonStyle ClickButtonStyle = new()
    {
        Width = 200,
        Height = 48,
        Color = Color.FromRgb(0x2563EB),
        ContentColor = Color.White,
        FontSize = 20,
        BorderRadius = 8,
        Padding = EdgeInsets.LeftRight(24),
        Resolve = (style, flags) =>
        {
            if ((flags & WidgetFlags.Disabled) != 0)
                return style with
                {
                    Color = Color.FromRgb(0x555555),
                    ContentColor = Color.FromRgb(0x999999),
                };
            if ((flags & WidgetFlags.Hovered) != 0)
                return style with
                {
                    Color = Color.FromRgb(0x3B82F6),
                    BorderWidth = 2,
                    BorderColor = Color.White,
                };
            return style;
        },
    };

    public void LoadAssets()
    {
        ExampleAssets.LoadAssets();
        _background = Asset.Load(AssetType.Texture, "background") as Texture;
    }

    public void Update()
    {
        Graphics.ClearColor = Color.FromRgb(0x0A0A1A);
    }

    public void UpdateUI()
    {
        // Full-screen background image
        if (_background != null)
            UI.Image(_background, BackgroundStyle);

        // Centered content on top
        using (UI.BeginContainer(RootStyle))
        {
            using (UI.BeginContainer(BoxStyle))
            {
                UI.Text("Hello World!", TitleStyle);

                if (_clickCount > 0)
                    UI.Text($"Clicked {_clickCount} time{(_clickCount != 1 ? "s" : "")}", CountStyle);

                if (UI.Button(new WidgetId(1), "Click Me", ClickButtonStyle))
                    _clickCount++;
            }
        }
    }
}
